# Generated by Django 2.2.5 on 2019-09-13 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Upfront',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recoupable', models.BooleanField()),
                ('projection', models.FloatField()),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Organizer')),
            ],
        ),
    ]
